AWSTemplateFormatVersion: 2010-09-09
Description: Echofish CloudFront

Parameters:
  UiBucketName:
    Type: String

Resources:

  UiCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref UiBucketName

  UiCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponsePagePath: /index.html
            ResponseCode: 200
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          MaxTTL: 3600
          MinTTL: 0
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Ref UiBucketName
          ViewerProtocolPolicy: https-only
        Origins:
          - DomainName: !Sub ${UiBucketName}.s3-${AWS::Region}.amazonaws.com
            Id: !Ref UiBucketName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${UiCloudFrontOai}
        PriceClass: PriceClass_100


  UiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UiBucketName
      PolicyDocument:
        Version: 2008-10-17
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Sid: '1'
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt UiCloudFrontOai.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub arn:${AWS::Partition}:s3:::${UiBucketName}/*


Outputs:
  UiCloudFrontDomain:
    Value: !GetAtt UiCloudFront.DomainName