AWSTemplateFormatVersion: 2010-09-09
Description: EchoFish Stack

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  ZarrBaseUrl:
    Description: The bucket HTTPS URL for the public dataset bucket
    Type: String
  RolePermissionsBoundary:
    Description: An optional permissions boundary to associate with the Lambda role
    Type: String
    Default: ""
  LogRetentionInDays:
    Description: The number of days to keep CloudWatch logs
    Type: Number
    MinValue: 0
    Default: 30

Conditions:
  CustomResourceLambdaIsRelease:
    Fn::Equals:
      - @CustomResourceLambda.version@
      - Fn::Join:
          - ""
          - Fn::Split:
              - "-SNAPSHOT"
              - @CustomResourceLambda.version@
  BucketDrainLambdaIsRelease:
    Fn::Equals:
      - @BucketDrainLambda.version@
      - Fn::Join:
          - ""
          - Fn::Split:
              - "-SNAPSHOT"
              - @BucketDrainLambda.version@
  UiIsRelease:
    Fn::Equals:
      - @ui.version@
      - Fn::Join:
          - ""
          - Fn::Split:
              - "-SNAPSHOT"
              - @ui.version@

Resources:

  BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentType:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-environment-type
        StackPrefix: !Ref StackPrefix
        PermissionsBoundary: !Ref RolePermissionsBoundary
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-deployment-bucket
        BucketDrainLambdaVersion: !If [ BucketDrainLambdaIsRelease, @BucketDrainLambda.version@, @BucketDrainLambda.version@@dashTimestamp@ ]
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/bucket-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-deployment-bucket

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        UiBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.UiBucketName
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/cloudfront-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-deployment-bucket

  UiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DeploymentBucketName:
          Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-deployment-bucket
        LambdaRolePermissionsBoundary: !Ref RolePermissionsBoundary
        UiVersion: !If [UiIsRelease, @ui.version@, @ui.version@@dashTimestamp@]
        UiDeploymentLambdaVersion: !If [ CustomResourceLambdaIsRelease, @CustomResourceLambda.version@, @CustomResourceLambda.version@@dashTimestamp@ ]
        UiBucketName:
          Fn::GetAtt:
            - BucketStack
            - Outputs.UiBucketName
        ZarrBaseUrl: !Ref ZarrBaseUrl
        StackPrefix: !Ref StackPrefix
      TemplateURL:
        Fn::Sub:
          - https://${DeploymentBucketName}.s3.${AWS::Region}.amazonaws.com/stack/nested/ui-stack.yaml
          - DeploymentBucketName:
              Fn::ImportValue: !Sub ${StackPrefix}-echofish-ui-deployment-bucket